config/urls.py
# ruff: noqa
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include
from django.urls import path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from drf_spectacular.views import SpectacularAPIView
from drf_spectacular.views import SpectacularSwaggerView
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/",
        TemplateView.as_view(template_name="pages/about.html"),
        name="about",
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("nems_proctor.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    # ...
    # Media files
    *static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT),
]
if settings.DEBUG:
    # Static file serving when using Gunicorn + Uvicorn for local web socket development
    urlpatterns += staticfiles_urlpatterns()

# API URLS
urlpatterns += [
    # API base url
    path("api/v1/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
    path("api/schema/", SpectacularAPIView.as_view(), name="api-schema"),
    path(
        "api/docs/",
        SpectacularSwaggerView.as_view(url_name="api-schema"),
        name="api-docs",
    ),
    path("api/v1/", include("nems_proctor.proctoring.api.urls")),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

nems_proctor/proctoring/api/urls.py
from django.urls import include
from django.urls import path
from rest_framework.routers import DefaultRouter

from .views import GetSessionsByExamAndTaker
from .views import GetSessionsPhotoBySession
from .views import GetSessionsRecordBySession
from .views import GetTakersByExam

router = DefaultRouter()


urlpatterns = [
    path("", include(router.urls)),
    path(
        "sessions/takers/<str:exam_code>/",
        GetTakersByExam.as_view(),
        name="get-takers-by-exam",
    ),
    path(
        "sessions/<int:session_id>/photos/",
        GetSessionsPhotoBySession.as_view(),
        name="get-session-photos-by-session",
    ),
    path(
        "sessions/<int:session_id>/records/",
        GetSessionsRecordBySession.as_view(),
        name="get-session-records-by-session",
    ),
    path(
        "sessions/<str:exam_code>/<str:taker_username>/",
        GetSessionsByExamAndTaker.as_view(),
        name="get-sessions-by-exam-and-taker",
    ),
]

nems_proctor/users/urls.py
from django.urls import path

from nems_proctor.users.views import user_detail_view
from nems_proctor.users.views import user_redirect_view
from nems_proctor.users.views import user_update_view

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

nems_proctor/face_recognition/models.py
# internal apps model

# Create models for

nems_proctor/proctoring/forms.py
from django import forms

from .models import SessionPhoto
from .models import SessionRecord


class SessionRecordForm(forms.ModelForm):
    """
    Form for uploading a recording associated with a session.
    """

    class Meta:
        model = SessionRecord
        fields = ["session", "recording_type", "file"]
        widgets = {
            "session": forms.Select(attrs={"class": "form-control"}),
            "recording_type": forms.Select(attrs={"class": "form-control"}),
            "file": forms.FileInput(attrs={"class": "form-control"}),
        }


class SessionPhotoForm(forms.ModelForm):
    """
    Form for uploading a photo for a session.
    """

    class Meta:
        model = SessionPhoto
        fields = ["session", "photo"]
        widgets = {
            "session": forms.Select(attrs={"class": "form-control"}),
            "photo": forms.FileInput(attrs={"class": "form-control"}),
        }

nems_proctor/proctoring/api/views.py
from django.db.models import Count
from django.db.models import Max
from django.shortcuts import get_object_or_404
from drf_spectacular.utils import OpenApiParameter
from drf_spectacular.utils import OpenApiTypes
from drf_spectacular.utils import extend_schema
from rest_framework import status
from rest_framework import viewsets
from rest_framework.decorators import action
from rest_framework.parsers import FormParser
from rest_framework.parsers import MultiPartParser
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework.views import APIView

from nems_proctor.proctoring.models import Exam
from nems_proctor.proctoring.models import Session
from nems_proctor.proctoring.models import SessionPhoto
from nems_proctor.proctoring.models import SessionRecord
from nems_proctor.users.models import User

from .serializers import ExamSerializer
from .serializers import GetTakersByExamSerializer
from .serializers import SessionPhotoCreateSerializer
from .serializers import SessionPhotoSerializer
from .serializers import SessionRecordCreateSerializer
from .serializers import SessionRecordSerializer
from .serializers import SessionSerializer

sort_param = OpenApiParameter(
    name="sort",
    type="string",
    enum=["asc", "desc"],
    default="asc",
    description="""
        Sort order for taker username.
        Values: 'asc' (ascending), 'desc' (descending).
        Default is 'asc'.
        """,
)


@extend_schema(
    parameters=[
        OpenApiParameter(
            name="taker",
            type=OpenApiTypes.STR,
            location=OpenApiParameter.QUERY,
            description="Filter sessions by taker username.",
        ),
        OpenApiParameter(
            name="exam",
            type=OpenApiTypes.STR,
            location=OpenApiParameter.QUERY,
            description="Filter sessions by exam code.",
        ),
        OpenApiParameter(
            name="proctor",
            type=OpenApiTypes.STR,
            location=OpenApiParameter.QUERY,
            description="Filter sessions by proctor username.",
        ),
    ],
    tags=["Session"],
)
class SessionViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows sessions to be viewed or edited.

    Query Parameters:
    - `taker`: Filter sessions by taker username.
    - `exam`: Filter sessions by exam code.
    - `proctor`: Filter sessions by proctor username.
    """

    queryset = Session.objects.all()
    serializer_class = SessionSerializer

    def get_queryset(self):
        queryset = super().get_queryset()
        taker_username = self.request.query_params.get("taker")
        exam_code = self.request.query_params.get("exam")
        proctor_username = self.request.query_params.get("proctor")

        if taker_username:
            queryset = queryset.filter(taker__username=taker_username)
        if exam_code:
            queryset = queryset.filter(exam__exam_code=exam_code)
        if proctor_username:
            queryset = queryset.filter(proctor__username=proctor_username)
        return queryset

    @action(detail=False, methods=["post"], url_path="start_session")
    def start_session(self, request):
        serializer = SessionSerializer(data=request.data)  # Use your updated serializer
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)

        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    @action(detail=True, methods=["post"], url_path="end_session")
    def end_session(self, request, pk=None):
        """
        Ends an active session. Only authenticated users can end sessions.
        """
        session = self.get_queryset().get(pk=pk)

        if not session.is_active:
            error_message = "This session is already closed."
            return Response(
                {"detail": f"{error_message}"},
                status=status.HTTP_400_BAD_REQUEST,
            )

        session.is_active = False
        session.save()

        return Response(
            {"detail": "Session successfully ended."},
            status=status.HTTP_200_OK,
        )

    @extend_schema(
        request=SessionPhotoCreateSerializer,
        responses={201: SessionPhotoCreateSerializer},
    )
    @action(
        detail=True,
        methods=["post"],
        url_path="add_photo",
        parser_classes=[MultiPartParser, FormParser],
    )
    def add_photo(self, request, pk=None):
        """
        Add a photo to an active session.

        An active session is required to add a new photo. If the session is closed,
        the operation will be rejected.
        """
        session = self.get_object()

        if not session.is_active:
            error_message = "This session has been closed and cannot accept new photo."
            return Response(
                {"detail": f"{error_message}"},
                status=status.HTTP_400_BAD_REQUEST,
            )

        serializer = SessionPhotoCreateSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save(session=session)
            return Response(serializer.data, status=status.HTTP_201_CREATED)

        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    @extend_schema(
        request=SessionRecordCreateSerializer,
        responses={201: SessionRecordCreateSerializer},
    )
    @action(
        detail=True,
        methods=["post"],
        url_path="add_record",
        parser_classes=[MultiPartParser, FormParser],
    )
    def add_record(self, request, pk=None):
        """
        API endpoint for managing session records.

        Provides standard model viewset actions
        for example: (list, create, retrieve, update, destroy)
        to work with session records.
        """
        session = self.get_object()

        if not session.is_active:
            error_message = "This session has been closed and cannot accept new record."
            return Response(
                {"detail": f"{error_message}"},
                status=status.HTTP_400_BAD_REQUEST,
            )

        serializer = SessionRecordCreateSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save(session=session)
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


@extend_schema(tags=["Session Record"])
class SessionRecordViewSet(viewsets.ModelViewSet):
    """
    API endpoint for managing session photos.

    Supports actions to list, create, retrieve, update, and delete session photos.
    """

    queryset = SessionRecord.objects.all()
    serializer_class = SessionRecordSerializer


@extend_schema(tags=["Session Photo"])
class SessionPhotoViewSet(viewsets.ModelViewSet):
    """
    API endpoint for managing session records.

    Supports actions to list, create, retrieve, update, and delete session photos.
    """

    queryset = SessionPhoto.objects.all()
    serializer_class = SessionPhotoSerializer


@extend_schema(tags=["Exam"])
class ExamViewSet(viewsets.ModelViewSet):
    """
    API endpoint for managing exams.

    Supports actions to list, create, retrieve, update, and delete exams.
    """

    queryset = Exam.objects.all()
    serializer_class = ExamSerializer
    permission_classes = [IsAuthenticated]

    def get_queryset(self):
        user_company_id = self.request.user.company_id
        return Exam.objects.filter(company_id=user_company_id)

    def perform_create(self, serializer):
        serializer.save(company_id=self.request.user.company_id)

    def perform_update(self, serializer):
        serializer.save(company_id=self.request.user.company_id)


@extend_schema(tags=["Session"])
class GetTakersByExam(APIView):
    serializer_class = GetTakersByExamSerializer

    def get(self, request, exam_code):
        exam = get_object_or_404(Exam, exam_code=exam_code)
        sessions = (
            Session.objects.filter(exam=exam)
            .values("taker")
            .annotate(attempts_count=Count("id"), latest_attempt=Max("start_time"))
            .order_by("taker")
        )

        # Map session data to taker IDs
        session_data_map = {session["taker"]: session for session in sessions}

        # Fetch the user instances
        user_ids = session_data_map.keys()
        users = User.objects.filter(id__in=user_ids)

        # Annotate users with session data
        for user in users:
            user_data = session_data_map.get(user.id)
            user.attempts_count = user_data["attempts_count"]
            user.latest_attempt = user_data["latest_attempt"]

        serializer = self.serializer_class(
            users,
            many=True,
            context={"request": request},
        )
        return Response(serializer.data)


@extend_schema(
    tags=["Session"],
    parameters=[
        OpenApiParameter(
            name="sort",
            type=OpenApiTypes.STR,
            description="""
            Sorts the sessions by ID.
            Use 'asc' for ascending or 'desc' for descending order.
            Default is 'asc'.
            """,
            required=False,
        ),
    ],
)
class GetSessionsByExamAndTaker(APIView):
    """
    Retrieve a list of sessions for a given exam code and taker username.

    This endpoint provides a list of sessions
    who have the specified exam code and taker username.
    """

    serializer_class = SessionSerializer

    def get(self, request, exam_code, taker_username):
        exam = get_object_or_404(Exam, exam_code=exam_code)
        taker = get_object_or_404(User, username=taker_username)

        sort_order = request.query_params.get("sort", "asc")
        order_by = "-id" if sort_order == "desc" else "id"

        sessions = Session.objects.filter(exam=exam, taker=taker).order_by(order_by)

nems_proctor/proctoring/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.shortcuts import render
from django.views import View
from django.views.generic.edit import CreateView
from django.views.generic.edit import UpdateView
from django.views.generic.list import ListView

from .forms import SessionPhotoForm  # Assuming you have these forms defined
from .forms import SessionRecordForm  # Assuming you have these forms defined
from .models import Exam
from .models import Session


class SessionListView(ListView):
    """
    View for listing all exam sessions.
    """

    model = Session
    template_name = "sessions/session_list.html"
    context_object_name = "sessions"


class SessionCreateView(CreateView):
    """
    View for creating a new exam session.
    """

    model = Session
    fields = ["exam", "taker", "proctor", "is_active"]
    template_name = "sessions/session_form.html"
    success_url = "/sessions/"

    def form_valid(self, form):
        # Additional processing can be done here if necessary
        return super().form_valid(form)


class SessionRecordUploadView(View):
    """
    View for uploading a recording associated with a session.
    """

    def get(self, request, *args, **kwargs):
        form = SessionRecordForm()
        return render(request, "sessions/sessionrecord_form.html", {"form": form})

    def post(self, request, *args, **kwargs):
        form = SessionRecordForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect("session_list")  # Redirect to the list of sessions
        return render(request, "sessions/sessionrecord_form.html", {"form": form})


class SessionPhotoUploadView(View):
    """
    View for uploading a photo for a session.
    """

    def get(self, request, *args, **kwargs):
        form = SessionPhotoForm()
        return render(request, "sessions/sessionphoto_form.html", {"form": form})

    def post(self, request, *args, **kwargs):
        form = SessionPhotoForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect("session_list")  # Redirect to the list of sessions
        return render(request, "sessions/sessionphoto_form.html", {"form": form})


class ExamCreateView(LoginRequiredMixin, CreateView):
    model = Exam
    fields = ["exam_title", "exam_code", "description"]

    def form_valid(self, form):
        form.instance.company_id = self.request.user.company_id
        return super().form_valid(form)


class ExamUpdateView(LoginRequiredMixin, UpdateView):
    model = Exam
    fields = ["exam_title", "exam_code", "description"]

    def form_valid(self, form):
        form.instance.company_id = self.request.user.company_id
        return super().form_valid(form)

nems_proctor/templates/403_csrf.html
{% extends "base.html" %}

{% block title %}
  Forbidden (403)
{% endblock title %}
{% block content %}
  <h1>Forbidden (403)</h1>
  <p>
    {% if exception %}
      {{ exception }}
    {% else %}
      You're not allowed to access this page.
    {% endif %}
  </p>
{% endblock content %}

nems_proctor/templates/base.html
{% load static i18n %}

<!DOCTYPE html>
{% get_current_language as LANGUAGE_CODE %}
<html lang="{{ LANGUAGE_CODE }}">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <title>
      {% block title %}
        nems-proctor
      {% endblock title %}
    </title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="Behold My Awesome Project!" />
    <meta name="author" content="Windalfin" />
    <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}" />
    {% block css %}
      <!-- Your stuff: Third-party CSS libraries go here -->
      <!-- This file stores project-specific CSS -->
      <link href="{% static 'css/project.min.css' %}" rel="stylesheet" />
    {% endblock css %}
    <!-- Le javascript
    ================================================== -->
    {# Placed at the top of the document so pages load faster with defer #}
    {% block javascript %}
      <!-- Vendor dependencies bundled as one file -->
      <script defer src="{% static 'js/vendors.min.js' %}"></script>
      <!-- place project specific Javascript in this file -->
      <script defer src="{% static 'js/project.min.js' %}"></script>
    {% endblock javascript %}
  </head>
  <body>
    <div class="mb-1">
      <nav class="navbar navbar-expand-md navbar-light bg-light">
        <div class="container-fluid">
          <button class="navbar-toggler navbar-toggler-right"
                  type="button"
                  data-bs-toggle="collapse"
                  data-bs-target="#navbarSupportedContent"
                  aria-controls="navbarSupportedContent"
                  aria-expanded="false"
                  aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <a class="navbar-brand" href="{% url 'home' %}">nems-proctor</a>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'home' %}">Home <span class="visually-hidden">(current)</span></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'about' %}">About</a>
              </li>
              {% if request.user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link"
                     href="{% url 'users:detail' request.user.username %}">{% translate "My Profile" %}</a>
                </li>
                <li class="nav-item">
                  {# URL provided by django-allauth/account/urls.py #}
                  <a class="nav-link" href="{% url 'account_logout' %}">{% translate "Sign Out" %}</a>
                </li>
              {% else %}
                {% if ACCOUNT_ALLOW_REGISTRATION %}
                  <li class="nav-item">
                    {# URL provided by django-allauth/account/urls.py #}
                    <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% translate "Sign Up" %}</a>
                  </li>
                {% endif %}
                <li class="nav-item">
                  {# URL provided by django-allauth/account/urls.py #}
                  <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% translate "Sign In" %}</a>
                </li>
              {% endif %}
            </ul>
          </div>
        </div>
      </nav>
    </div>
    <div class="container">
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-dismissible {% if message.tags %}alert-{{ message.tags }}{% endif %}">
            {{ message }}
            <button type="button"
                    class="btn-close"
                    data-bs-dismiss="alert"
                    aria-label="Close"></button>
          </div>
        {% endfor %}
      {% endif %}
      {% block content %}
        <p>Use this document as a way to quick start any new project.</p>
      {% endblock content %}
    </div>
    <!-- /container -->
    {% block modal %}
    {% endblock modal %}
    {% block inline_javascript %}
      {% comment %}
    Script tags with only code, no src (defer by default). To run
    with a "defer" so that you run inline code:
    <script>
      window.addEventListener('DOMContentLoaded', () => {
        /* Run whatever you want */
      });
    </script>
      {% endcomment %}
    {% endblock inline_javascript %}
  </body>
</html>